dist: trusty
language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer self-update || true
    - composer install --dev --prefer-dist

script:
    - vendor/bin/atoum
